name: flutter_paginator_ns
description: A customizable pagination package for Flutter. This package can be used to fetch and display data from an API page by page.
version: 2.0.0
homepage: https://github.com/bernardoveras/FlutterPaginator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: